name:                fmt-for-rio
version:             1.0.0.0
github:              "cdornan/fmt-for-rio"
license:             BSD3
author:              "Chris Dornan"
maintainer:          "chris@chrisdornan.com"
copyright:           "2019 Chris Dornan"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Adaptor for getting fmt to work with rio
category:            Control, Text

description:         Please see the README on GitHub at <https://github.com/cdornan/fmt-for-rio#readme>

dependencies:
- base          >= 4.10 && < 10
- enum-text-rio >= 1.2.0.0

ghc-options:
- -Wall

library:
  source-dirs: src
